### ISSUE TITLE
Django 1.10 Compatibility

### ISSUE THREAD

**Issue by joaonrb** [matannoam/pypugjs#4]
The framework is currently not working with Django 1.10. 

So far the only error I had is:

```
Traceback (most recent call last):
  File "/opt/project/env/lib/python3.5/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/opt/project/env/lib/python3.5/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  (...)
  File "/opt/project/env/lib/python3.5/site-packages/django/template/loader.py", line 67, in render_to_string
    template = get_template(template_name, using=using)
  File "/opt/project/env/lib/python3.5/site-packages/django/template/loader.py", line 18, in get_template
    engines = _engine_list(using)
  File "/opt/project/env/lib/python3.5/site-packages/django/template/loader.py", line 72, in _engine_list
    return engines.all() if using is None else [engines[using]]
  File "/opt/project/env/lib/python3.5/site-packages/django/template/utils.py", line 89, in all
    return [self[alias] for alias in self]
  File "/opt/project/env/lib/python3.5/site-packages/django/template/utils.py", line 89, in <listcomp>
    return [self[alias] for alias in self]
  File "/opt/project/env/lib/python3.5/site-packages/django/template/utils.py", line 80, in __getitem__
    engine = engine_cls(params)
  File "/opt/project/env/lib/python3.5/site-packages/django/template/backends/django.py", line 32, in __init__
    self.engine = Engine(self.dirs, self.app_dirs, **options)
  File "/opt/project/env/lib/python3.5/site-packages/django/template/engine.py", line 50, in __init__
    self.template_builtins = self.get_template_builtins(self.builtins)
  File "/opt/project/env/lib/python3.5/site-packages/django/template/engine.py", line 94, in get_template_builtins
    return [import_library(x) for x in builtins]
  File "/opt/project/env/lib/python3.5/site-packages/django/template/engine.py", line 94, in <listcomp>
    return [import_library(x) for x in builtins]
  File "/opt/project/env/lib/python3.5/site-packages/django/template/library.py", line 325, in import_library
    "trying to load '%s': %s" % (name, e)
django.template.library.InvalidTemplateLibrary: Invalid template library specified. ImportError raised when trying to load 'pypugjs.ext.django.templatetags': cannot import name 'BaseLoader'
```

**Comment by Hum4n01d** [comment]
Please fix this :)
