### ISSUE TITLE
include does not work with plain text

### ISSUE THREAD

**Issue by andredias** [matannoam/pypugjs#6]
The plain text examples of the include directive  in https://pugjs.org/language/includes.html do not work!

```
//- index.pug
doctype html
html
  head
    style
      include style.css
  body
    h1 My Site
    p Welcome to my super lame site.
    script
      include script.js
```

```css
/* style.css */
h1 {
  color: red;
}
```

```javascript
// script.js
console.log('You are awesome');
```

The expected result is:

```html
<!DOCTYPE html>
<html>

<head>
  <style>
    /* style.css */
    
    h1 {
      color: red;
    }
  </style>
</head>

<body>
  <h1>My Site</h1>
  <p>Welcome to my super lame site.</p>
  <script>
    // script.js
    console.log('You are awesome');
  </script>
</body>

</html>
```

but what I've got instead is:

```html
<!DOCTYPE html>
<html>
  <head>
    <style>
      <h1>{
        <color>
          <red>;</red>
        </color>
      </h1>}

    </style>
  </head>
  <body>
    <h1>My Site</h1>
    <p>Welcome to my super lame site.</p>
    <script>
      <!-- script.js-->
      <console You are awesome class="log">;</console>
    </script>
  </body>
</html>
```

----

Another example:

```
doctype html
html
body
    include drawing.svg
```

drawing.svg:

```html
<svg xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#" xmlns="http://www.w3.org/2000/svg" height="41mm" width="41mm" version="1.1" xmlns:cc="http://creativecommons.org/ns#" xmlns:dc="http://purl.org/dc/elements/1.1/" viewBox="0 0 144.4 144.3">
 <g transform="translate(-270.7,-374.4)">
  <circle stroke-linejoin="round" style="color-rendering:auto;color:#000000;isolation:auto;mix-blend-mode:normal;shape-rendering:auto;solid-color:#000000;image-rendering:auto" cx="3.4e2" stroke-linecap="round" stroke="#808000" cy="4.5e2" r="71" stroke-miterlimit="3" stroke-width="1.5" fill="#ffff7d"/>
 </g>
</svg>
```

The output:

```
WARNING:root:No module named 'django'
WARNING:root:No module named 'tornado'
Traceback (most recent call last):
  File "/home/andref/.virtualenvs/home_page/bin/pypugjs", line 11, in <module>
    sys.exit(convert_file())
  File "/home/andref/.virtualenvs/home_page/lib/python3.5/site-packages/pypugjs/convert.py", line 58, in convert_file
    staticAttrs=True, extension=extension)
  File "/home/andref/.virtualenvs/home_page/lib/python3.5/site-packages/pypugjs/utils.py", line 230, in process
    return _compiler.compile().strip()
  File "/home/andref/.virtualenvs/home_page/lib/python3.5/site-packages/pypugjs/compiler.py", line 91, in compile
    self.visit(self.node)
  File "/home/andref/.virtualenvs/home_page/lib/python3.5/site-packages/pypugjs/compiler.py", line 121, in visit
    self.visitNode(node, *args, **kwargs)
  File "/home/andref/.virtualenvs/home_page/lib/python3.5/site-packages/pypugjs/compiler.py", line 129, in visitNode
    return getattr(self, 'visit%s' % name)(node, *args, **kwargs)
  File "/home/andref/.virtualenvs/home_page/lib/python3.5/site-packages/pypugjs/compiler.py", line 136, in visitBlock
    self.visit(node)
  File "/home/andref/.virtualenvs/home_page/lib/python3.5/site-packages/pypugjs/compiler.py", line 121, in visit
    self.visitNode(node, *args, **kwargs)
  File "/home/andref/.virtualenvs/home_page/lib/python3.5/site-packages/pypugjs/compiler.py", line 129, in visitNode
    return getattr(self, 'visit%s' % name)(node, *args, **kwargs)
  File "/home/andref/.virtualenvs/home_page/lib/python3.5/site-packages/pypugjs/compiler.py", line 201, in visitTag
    self.visit(tag.block)
  File "/home/andref/.virtualenvs/home_page/lib/python3.5/site-packages/pypugjs/compiler.py", line 121, in visit
    self.visitNode(node, *args, **kwargs)
  File "/home/andref/.virtualenvs/home_page/lib/python3.5/site-packages/pypugjs/compiler.py", line 129, in visitNode
    return getattr(self, 'visit%s' % name)(node, *args, **kwargs)
  File "/home/andref/.virtualenvs/home_page/lib/python3.5/site-packages/pypugjs/compiler.py", line 136, in visitBlock
    self.visit(node)
  File "/home/andref/.virtualenvs/home_page/lib/python3.5/site-packages/pypugjs/compiler.py", line 121, in visit
    self.visitNode(node, *args, **kwargs)
  File "/home/andref/.virtualenvs/home_page/lib/python3.5/site-packages/pypugjs/compiler.py", line 129, in visitNode
    return getattr(self, 'visit%s' % name)(node, *args, **kwargs)
  File "/home/andref/.virtualenvs/home_page/lib/python3.5/site-packages/pypugjs/ext/html.py", line 86, in visitInclude
    block = parser.parse()
  File "/home/andref/.virtualenvs/home_page/lib/python3.5/site-packages/pypugjs/parser.py", line 46, in parse
    else: block.append(self.parseExpr())
  File "/home/andref/.virtualenvs/home_page/lib/python3.5/site-packages/pypugjs/parser.py", line 87, in parseExpr
    (t, self.filename, self.line()))
Exception: unexpected token "indent" in file None on line 2
```

**Comment by matannoam** [comment]
This is part of a larger issue - right now PyPugJS is just PyJade with the name changed. In the future, I'd like it to be able to parse the PugJS version of the syntax.

**Comment by mustefa** [comment]
is there noone properly using pug in django without errors?
